dkim_sign: Buffer.concat expects an array of buffers
Bug reported on IRC by DarkSorrow:

`````
[DEBUG] [F998D59E-CB9B-47F3-8056-736D91D0B8CF.1] [core] running queue_outbound hook in dkim_sign plugin
[CRIT] [-] [core] TypeError: undefined is not a function
[CRIT] [-] [core]     at Function.Buffer.concat (buffer.js:267:9)
[CRIT] [-] [core]     at DKIMSignStream.end (/data/src/Haraka/dkim_sign.js:87:25)
[CRIT] [-] [core]     at MessageStream.onend (stream.js:60:10)
[CRIT] [-] [core]     at emitNone (events.js:72:20)
[CRIT] [-] [core]     at MessageStream.emit (events.js:163:7)
[CRIT] [-] [core]     at /data/src/Haraka/messagestream.js:318:14
[CRIT] [-] [core]     at ChunkEmitter.end (/data/src/Haraka/chunkemitter.js:101:41)
[CRIT] [-] [core]     at MessageStream._read_finish (/data/src/Haraka/messagestream.js:310:18)
[CRIT] [-] [core]     at MessageStream._read (/data/src/Haraka/messagestream.js:245:18)
[CRIT] [-] [core]     at /data/src/Haraka/messagestream.js:233:22
[NOTICE] [-] [core] Shutting down
`````